name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
    contents: read
    packages: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        target:
          - arch: aarch64-apple-darwin
            runs-on: macos-latest
    runs-on: ${{ matrix.target.runs-on }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Prepare target
        run: rustup target add ${{ matrix.target.arch }}
      - name: Set Rust version
        run: rustup override set stable
      - name: Update assets
        run: ./update_assets.sh
      - name: Install cargo-auditable
        run: cargo install cargo-auditable
      - name: Build
        run: cargo auditable build --target=${{ matrix.target.arch }} --release --verbose
      - name: Archive csaf-validator (${{ matrix.target.arch }})
        uses: actions/upload-artifact@v4
        with:
          name: csaf-validator-${{ matrix.target.arch }}
          path: target/${{ matrix.target.arch }}/release/csaf-validator${{ matrix.target.ext }}
      - name: Generate CycloneDX SBOM
        uses: anchore/sbom-action@v0
        with:
          file: ./target/${{ matrix.target.arch }}/release/csaf-validator${{ matrix.target.ext }}
          format: cyclonedx-json
          artifact-name: csaf-validator-${{ matrix.target.arch }}-sbom.cdx.json
      - name: Generate SPDX SBOM
        uses: anchore/sbom-action@v0
        with:
          file: ./target/${{ matrix.target.arch }}/release/csaf-validator${{ matrix.target.ext }}
          format: spdx-json
          artifact-name: csaf-validator-${{ matrix.target.arch }}-sbom.spdx.json

  devguard-secret-scanning:
    uses: l3montree-dev/devguard-action/.github/workflows/secret-scanning.yml@main
    with:
      #api-url: https://api.devguard.org 
      asset-name: ${{ vars.DEVGUARD_ASSET }}
    secrets:
      devguard-token: ${{ secrets.DEVGUARD_TOKEN }}
  
  devguard-sast: #uses semgrep
    uses: l3montree-dev/devguard-action/.github/workflows/static-application-security-testing.yml@main
    with:
      #api-url: https://api.devguard.org 
      asset-name: ${{ vars.DEVGUARD_ASSET }}
    secrets:
      devguard-token: ${{ secrets.DEVGUARD_TOKEN }}
    
  devguard-sca: #uses trivy
    uses: l3montree-dev/devguard-action/.github/workflows/software-composition-analysis.yml@main
    with:
      #api-url: https://api.devguard.org 
      asset-name: ${{ vars.DEVGUARD_ASSET }}
    secrets:
      devguard-token: ${{ secrets.DEVGUARD_TOKEN }}

  devguard-iac: # uses checkov
    uses: l3montree-dev/devguard-action/.github/workflows/iac.yml@main
    with:
      #api-url: https://api.devguard.org 
      asset-name: ${{ vars.DEVGUARD_ASSET }}
    secrets:
      devguard-token: ${{ secrets.DEVGUARD_TOKEN }}

  #dependency-risk-identification:
  #  needs: build
  #  uses: l3montree-dev/devguard-action/.github/workflows/dependency-risk-identification.yml@main
  #  with:
  #    #api-url: https://api.devguard.org 
  #    asset-name: ${{ vars.DEVGUARD_ASSET }}
  #    sbom-artifact-name: csaf-validator-aarch64-apple-darwin-sbom.cdx.json
  #    sbom-file: csaf-validator-aarch64-apple-darwin-sbom.cdx.json
  #  secrets:
  #    devguard-token: ${{ secrets.DEVGUARD_TOKEN }}
  
  #call-devsecops: # not working because we have no image
  #  needs: build
  #  uses: l3montree-dev/devguard-action/.github/workflows/full.yml@main
  #  with:
  #    asset-name: "csaf-rs-test/projects/test/assets/csaf-test-private"
  #    api-url: "https://api.devguard.org"
  #    web-ui: "https://app.devguard.org"
  #  secrets:
  #    devguard-token: "${{ secrets.DEVGUARD_TOKEN }}" # you need to create this secret in your GitHub repository settings

  #code-risk-identification:
  #  needs: build
  #  uses: l3montree-dev/devguard-action/.github/workflows/upload-sbom.yml@main
  #  with:
  #    # Path to SBOM file relative to the root of the repository
  #    sbom-file: ./results.sbom
  #    asset-name: "csaf-rs-test/projects/test/assets/csaf-test-private"
  #    api-url: "https://api.devguard.org"
  #    web-ui: "https://app.devguard.org"
  #  secrets:
  #    devguard-token: "${{ secrets.DEVGUARD_TOKEN }}" # you need to create this secret in your GitHub repository settings 
