name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
    contents: read
    packages: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        version:
          - 1.88.0
          - 1.93.0
        target:
          - arch: aarch64-apple-darwin
            runs-on: macos-latest
          - arch: x86_64-unknown-linux-gnu
            runs-on: ubuntu-latest
          - arch: x86_64-pc-windows-msvc
            runs-on: windows-latest
            ext: .exe
    runs-on: ${{ matrix.target.runs-on }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Set Rust version
        run: |
          rustup override set ${{ matrix.version }}
          rustup default ${{ matrix.version }}
      - name: Prepare target
        run: rustup target add ${{ matrix.target.arch }}
      - name: Get version
        id: version
        run: |
          VERSION=$(cargo metadata --no-deps --format-version=1 | jq -r '.packages[] | select(.name == "csaf-validator") | .version')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Use cache
        uses: Swatinem/rust-cache@v2
        with:
          key: build-${{matrix.version}}-${{ matrix.target.arch }}-${{ steps.version.outputs.version }}
      - name: Update assets
        run: ./update_assets.sh
      - name: Install cargo-auditable
        run: cargo install cargo-auditable
      - name: Build
        run: cargo auditable build --target=${{ matrix.target.arch }} --release --locked --verbose
      - name: Archive csaf-validator (${{ matrix.target.arch }})
        uses: actions/upload-artifact@v4
        with:
          name: csaf-validator-${{ matrix.target.arch }}-${{ matrix.version }}-v${{ steps.version.outputs.version }}
          path: target/${{ matrix.target.arch }}/release/csaf-validator${{ matrix.target.ext }}
      - name: Generate CycloneDX SBOM
        uses: anchore/sbom-action@v0
        with:
          file: ./target/${{ matrix.target.arch }}/release/csaf-validator${{ matrix.target.ext }}
          format: cyclonedx-json
          artifact-name: csaf-validator-${{ matrix.target.arch }}-${{ matrix.version }}-v${{ steps.version.outputs.version }}-sbom.cdx.json
      - name: Generate SPDX SBOM
        uses: anchore/sbom-action@v0
        with:
          file: ./target/${{ matrix.target.arch }}/release/csaf-validator${{ matrix.target.ext }}
          format: spdx-json
          artifact-name: csaf-validator-${{ matrix.target.arch }}-${{ matrix.version }}-v${{ steps.version.outputs.version }}-sbom.spdx.json

  devguard-secret-scanning: # uses gitleaks
    uses: l3montree-dev/devguard-action/.github/workflows/secret-scanning.yml@main
    with:
      #api-url: https://api.devguard.org 
      asset-name: ${{ vars.DEVGUARD_ASSET }}
    secrets:
      devguard-token: ${{ secrets.DEVGUARD_TOKEN }}
  
  devguard-sast: #uses semgrep
    uses: l3montree-dev/devguard-action/.github/workflows/static-application-security-testing.yml@main
    with:
      #api-url: https://api.devguard.org 
      asset-name: ${{ vars.DEVGUARD_ASSET }}
    secrets:
      devguard-token: ${{ secrets.DEVGUARD_TOKEN }}
    
  # devguard-sca: #uses trivy
  #   uses: l3montree-dev/devguard-action/.github/workflows/software-composition-analysis.yml@main
  #   with:
  #     #api-url: https://api.devguard.org 
  #     asset-name: ${{ vars.DEVGUARD_ASSET }}
  #   secrets:
  #     devguard-token: ${{ secrets.DEVGUARD_TOKEN }}

  devguard-iac: # uses checkov
    uses: l3montree-dev/devguard-action/.github/workflows/iac.yml@main
    with:
      #api-url: https://api.devguard.org 
      asset-name: ${{ vars.DEVGUARD_ASSET }}
    secrets:
      devguard-token: ${{ secrets.DEVGUARD_TOKEN }}
  
  process-sboms:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all CDX artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: '*-sbom.cdx.json'
          path: sboms/
      
      - name: Process CDX files
        uses:  docker://ghcr.io/l3montree-dev/devguard/scanner:main-latest 
        with:
          args: |
            for cdx_file in sboms/**/*.cdx.json; do
              echo "Processing: $cdx_file"
              
              # Remove prefix and suffix to extract arch and version
              temp="${cdx_file#csaf-validator-}"
              temp="${temp%-sbom.cdx.json}"
              
              # Split by last dash to separate arch and version
              arch="${temp%-*}"
              version="${temp##*-}"
              
              echo "Architecture: $arch"
              echo "Version: $version"
              

              # TODO: Call your action here with the extracted information
              # Example:
              # - uses: your-action@v1
              #   with:
              #     cdx-file: $cdx_file
              #     architecture: $arch
              #     version: $version
            done
  
  #devguard-sbom-attestation:
  #  needs: build
   # runs-on: ubuntu-latest
   # steps:
   #   - name: download
   #     uses: actions/download-artifact@v4
   #     with:
   #       name: csaf-validator-aarch64-apple-darwin-sbom.cdx.json
   #   - name: attestation
   #     uses:  docker://ghcr.io/l3montree-dev/devguard/scanner:main-latest 
   #     with:
   #       #args: devguard-scanner secret-scanning --assetName=${{ inputs.asset-name }} --apiUrl=${{ inputs.api-url }} --token="${{ secrets.devguard-token }}" --path=${{ inputs.path }} --defaultRef=${{ github.event.repository.default_branch }} --isTag=${{ github.ref_type == 'tag' }} --ref=${{ github.ref_name }} --webUI=${{ inputs.web-ui }}
   #       args: devguard-scanner attest --assetName=${{ vars.DEVGUARD_ASSET }} --token "${{ secrets.DEVGUARD_TOKEN }}" --predicateType "https://cyclonedx.org/bom" --artifactName source csaf-validator-aarch64-apple-darwin-sbom.cdx.json#
