name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        target:
          - arch: x86_64-unknown-linux-gnu
            runs-on: ubuntu-latest
          - arch: aarch64-apple-darwin
            runs-on: macos-latest
    runs-on: ${{ matrix.target.runs-on }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Prepare target
        run: rustup target add ${{ matrix.target.arch }}
      - name: Set Rust version
        run: rustup override set stable
      - name: Update assets
        run: ./update_assets.sh
      - name: Install cargo-auditable
        run: cargo install cargo-auditable
      - name: Build
        run: cargo auditable build --target=${{ matrix.target.arch }} --release --verbose
      - name: Archive csaf-validator (${{ matrix.target.arch }})
        uses: actions/upload-artifact@v4
        with:
          name: csaf-validator-${{ matrix.target.arch }}-${{ matrix.version }}
          path: target/${{ matrix.target.arch }}/release/csaf-validator${{ matrix.target.ext }}
      - name: Generate CycloneDX SBOM
        uses: anchore/sbom-action@v0
        with:
          file: ./target/${{ matrix.target.arch }}/release/csaf-validator${{ matrix.target.ext }}
          format: cyclonedx-json
          artifact-name: csaf-validator-${{ matrix.target.arch }}-${{ matrix.version }}-sbom.cdx.json
      - name: Generate SPDX SBOM
        uses: anchore/sbom-action@v0
        with:
          file: ./target/${{ matrix.target.arch }}/release/csaf-validator${{ matrix.target.ext }}
          format: spdx-json
          artifact-name: csaf-validator-${{ matrix.target.arch }}-${{ matrix.version }}-sbom.spdx.json
